### ISSUE TITLE
Personal info etc. not updating after introduction of Themes

### ISSUE THREAD

**Issue by Mathyy** [StratusNetwork/Issues#103]
Profile information such as 'Personal' and 'Other Accounts' etc. won't update after the introduction of Themes.

When trying to update your information it only gives a message saying "Invalid theme specified" as shown in the image.
![invalid theme specified](https://user-images.githubusercontent.com/32422229/31049524-1eac4fda-a635-11e7-8418-fb0c5a731cd3.png)

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
Fixed in StratusNetwork/OCN#18
