### ISSUE TITLE
The more selection thing on page selection needs to be recoloured in dark mode

### ISSUE THREAD

**Issue by CrazyisCreeps** [StratusNetwork/Issues#105]
Idk what you call it, but this. https://gyazo.com/f6c276c61c3193268fd43365937a8833

found on https://stratus.network/punishments

**Comment by Matic0B** [comment]
https://github.com/StratusNetwork/OCN/pull/16

**Comment by Matic0B** [comment]
https://github.com/StratusNetwork/OCN/pull/19
