### ISSUE TITLE
Weird sounds of items that goes to the inventory even if there is no items on the floor

### ISSUE THREAD

**Issue by unixfox** [StratusNetwork/Issues#108]
When playing on 1.7 and 1.8 I hear the sound of "items that goes to the inventory" even if there is no items on the floor.

Here is a video about this issue on Youtube:
[![Youtube video](https://img.youtube.com/vi/tMzGn0E3t10/0.jpg)](https://www.youtube.com/watch?v=tMzGn0E3t10)

**Comment by Brottweiler** [comment]
Fixed.
