### ISSUE TITLE
Dark theme missing features

### ISSUE THREAD

**Issue by eudaldca** [StratusNetwork/Issues#109]
- [x] appeals, reports, and infractions lists appear too bright, may look better in a darker tone? (especially escalated yellow)
- [x] Some text labels should probably be changed to black text (see below [1] vs [2])
View appeal and report text appears white (probably known) [3]
- [x] Issue punishment box needs dark magic [4]
- [x] Friends page's avatars have white borders [5]
- [x] Sessions page
- [x] IP bans page's IPs look too bright (is it worth changing them?)
[1]
![image](https://user-images.githubusercontent.com/8332105/31256338-29e40a22-aa32-11e7-8af0-557342b5c27a.png)
[2]
![image](https://user-images.githubusercontent.com/8332105/31256352-48a1a0aa-aa32-11e7-96c1-c4e2800885a8.png)
[3]
![image](https://user-images.githubusercontent.com/8332105/31256409-abca6a2c-aa32-11e7-93b1-bb46af59dc97.png) ![image](https://user-images.githubusercontent.com/8332105/31256418-b83f65fa-aa32-11e7-84ac-0cc47da2c63a.png)
[4]
![image](https://user-images.githubusercontent.com/8332105/31256478-128ed748-aa33-11e7-8d80-bc02b907cca3.png)
[5]
![image](https://user-images.githubusercontent.com/8332105/31256540-7953d5f0-aa33-11e7-9d00-ad7374b5a75f.png)

**Comment by eudaldca** [comment]
@Matic0B

**Comment by Matic0B** [comment]
@Eudaldca Could you provide images of sessions and ip bans (without the confidential information)? (can't check sessions on localhost cause I dont have a pgm server running, ip bans seem ok to me)

**Comment by Matic0B** [comment]
https://github.com/StratusNetwork/OCN/pull/19
