### ISSUE TITLE
Adding friends on the forums doesn't work

### ISSUE THREAD

**Issue by CrazyisCreeps** [StratusNetwork/Issues#117]
When you hit the 'Add friend' button on the forums, it redirects you to the friends page, and the friend request does not go through. 

For example, when trying to add https://stratus.network/Happyprinces_22 as a friend, I was redirected to `https://stratus.network/friendships?user_id=58d8627ef6e8a82e20001f3a` https://gyazo.com/a3c1a2bdb4e34be9bc57c5a9dc98fa59

**Comment by Matic0B** [comment]
Happens when the page isn't fully loaded. Can't reproduce if the page is fully loaded.
