### ISSUE TITLE
Game doesn't skip if nobody joins

### ISSUE THREAD

**Issue by ItzCal** [StratusNetwork/Issues#12]
enderdragon bar should countdown if nobody joins

![2017-02-16_19 58 54](https://cloud.githubusercontent.com/assets/22266452/23038825/50ad03f8-f483-11e6-95ed-194f23f247de.png)

**Comment by amactus** [comment]
This is only a feature on Ranked games, it's never been a part of public OCN. Do you feel it should be changed regardless?

**Comment by amactus** [comment]
No Response
