### ISSUE TITLE
Can't leave the match to go to spectator

### ISSUE THREAD

**Issue by benrobson** [StratusNetwork/Issues#120]
[![Screenshot from Gyazo](https://gyazo.com/fc60750e88bb5acc1c068a8f4e2c3ecf/raw)](https://gyazo.com/fc60750e88bb5acc1c068a8f4e2c3ecf)

**Comment by Matic0B** [comment]
You can do /obs until this is addressed

**Comment by jexeI** [comment]
#7 Has the similar effect, but denies the action instead of only broadcasting the message to the player.
