### ISSUE TITLE
The maps page contains a small error; the text is not centered.

### ISSUE THREAD

**Issue by AbusiveUser** [StratusNetwork/Issues#122]
This is an example of the issue. It's the first time I see this and only happens on the "Now Playing" tab.

![8fa56f85e3d646b5e01101c4cbb74bf5](https://user-images.githubusercontent.com/19915020/32686953-8ba91a08-c676-11e7-9c26-a8d2508f33f2.png)

**Comment by Matic0B** [comment]
The text would be centered if the image for the map loaded
