### ISSUE TITLE
Add Languages to player profiles

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/Issues#123]
Add a field for which languages players speak on profiles.

**Comment by HuManKeat** [comment]
instead of this, why not allow the player to set their own preferred language and show them the translated web instead, using OCN's ready-available translation files.

**Comment by Matic0B** [comment]
@PotatoStealer I'd like something like that but showing a languages field on profiles would also make things easier for players looking for a team. But I agree with offering a translated version of the website.
