### ISSUE TITLE
Gralien: wrong placement of signs (spawn).

### ISSUE THREAD

**Issue by AbusiveUser** [StratusNetwork/Issues#127]
As you can see on the image below, it says you can place the pink wool there but when you try, it gives you an error. Same happens with the Magenta sign.

You guys can fix the signs or fix the coordinates on the XML. 

![2017-11-22_23 10 33](https://user-images.githubusercontent.com/19915020/33159820-6794fee2-cfdc-11e7-9f50-2702cb150521.png)
![2017-11-22_23 10 29](https://user-images.githubusercontent.com/19915020/33159821-67a6c820-cfdc-11e7-8e20-168527f6ca76.png)

**Comment by jexeI** [comment]
Fixed, along with some indentation and minor tweaks to the XML.
