### ISSUE TITLE
Appeals page layout is broken

### ISSUE THREAD

**Issue by eudaldca** [StratusNetwork/Issues#130]
Edit: Screenshot on Chrome. Safari and Firefox Quantum 85.0b6 work as expected.

![image](https://user-images.githubusercontent.com/8332105/33244579-906424b2-d2fa-11e7-99e3-523afb074e2f.png)

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
Not in Firefox Quantum 58.0b6
![okcorgg 1](https://user-images.githubusercontent.com/1473832/33244961-7d12ab52-d301-11e7-8b16-df79b6a02fe8.png)

**Comment by Matic0B** [comment]
Broken on Chrome at least

**Comment by amactus** [comment]
This should be fixed as of a while ago.

**Comment by eudaldca** [comment]
It isn't, Chrome 70.0.3538.77 on Windows
![image](https://user-images.githubusercontent.com/8332105/47955694-f2b9fc00-df9b-11e8-9421-3204f0e7e998.png)
