### ISSUE TITLE
Projectiles get stuck at some point when going into the void

### ISSUE THREAD

**Issue by BGMP** [StratusNetwork/Issues#132]
When projectiles are thrown (including arrows) by a player, the projectile will stay loaded in the world since the server render distance is low, and may only drop into the void when players get near it.

[Here's a video were Jexel and I reproduced this on Dynamo](https://www.youtube.com/watch?v=lpj5TSTxZ9k)

**Comment by jexeI** [comment]
Tested on a public server with mass amounts of snowballs, it is indeed the reason why the server is lagging and why players are getting disconnected. The lag fixes itself once the chunks that the projectiles are in is loaded by standing within the chunk as a player.

**Comment by amactus** [comment]
I'm 84% sure this is fixed but idk

**Comment by jexeI** [comment]
@amactus this was fixed when the render distance was extended back to normal
