### ISSUE TITLE
Tools not on item repair on Xi II

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/Issues#135]
Iron sword
Bow
Iron Pick
Iron Axe

Blocks aren't on itemremove either, not sure if thats intended

**Comment by BGMP** [comment]
I have fixed both of the problems, basically <tools/> were inside the wrong module.

Fixed in: https://gitlab.com/stratus/maps/commit/a25d955d8ca815907fe0d7ebc889c7ceeac8c430
