### ISSUE TITLE
Beta - No easy way to tell what a person's email or discord is

### ISSUE THREAD

**Issue by Classicallama** [StratusNetwork/Issues#136]
^ The rest of the social media's lead to links, however since email and discord doesn't it's hard to tell what a person's info is. It's even more of a pain to get it once you find it (since it appears when you highlight the button) because there's no way to copy or paste the info.

Maybe clicking the button can open a pop-up with the info?

**Comment by Matic0B** [comment]
Email leads to a "mailto:", discord is known and will be improved (but is currently displayed if its moused over)
