### ISSUE TITLE
Flag Beacon hard to see [Christmas Sanctuary]

### ISSUE THREAD

**Issue by BTKingly** [StratusNetwork/Issues#138]
With all the snow fall, it's hard to identify the white flag beacon

**Comment by Palmidence** [comment]
I'll consider this a bug as it is a huge inconvenience.

**Comment by BGMP** [comment]
I have changed the Flag color to orange and it's now more visible.

![2017-12-09_22 49 30](https://user-images.githubusercontent.com/26081543/33801244-aaf78682-dd33-11e7-8137-b16a06fd2a8b.png)
