### ISSUE TITLE
Hemlock II is broken

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#143]
- You can break blocks other than webs in the wool rooms
- There isn't any wool room gear in the wool rooms
- There is still white stained glass in one lane of the map (make block 36)
- Teams are missing armor (helmet, chestplate, leggings, iron boots)
- You can't build on bedrock level (because of block 36)

**Comment by BGMP** [comment]
I have Fixed all of the issues.

Fixed by: https://gitlab.com/stratus/maps/commit/e3d00e5cefd2eabff01b81ae4271cc2ed2e400fb
