### ISSUE TITLE
Add new functions to markdown "new post" editor

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#145]
(Was told to post this)

Matic expressed interest in adding the following functions to the post editor:

- [ ] Underline
- [ ] Strikethrough

- [ ] Subscript
- [ ] Superscript

![image](https://user-images.githubusercontent.com/17485345/33911675-14af31ea-df61-11e7-8e6f-f4cfae5c2ab9.png)

This would be to improve posting on the forums, especially since these basic functions are important.

**Comment by Szboy** [comment]
If I recall correctly there isn't a native underline in markdown, thus why it wasn't added to begin with when it was implemented back on the ocn forums.

**Comment by Palmidence** [comment]
@Szboy Yeah, he was aware. I think we can look into a custom implementation in the future, as markdown is usually modified by many sites.
