### ISSUE TITLE
Race┈for┈Victory:┈Redux custom rules don't match with Race┈for┈Victory

### ISSUE THREAD

**Issue by BTKingly** [StratusNetwork/Issues#147]
Under /map, Race┈for┈Victory:Redux does not have the rule "Players may not venture below the bottom bedrock layer of the map.", but the original does. This could lead to some confusion between the two. (Of course, this might be intentional, but I have no idea).

Original: https://imgur.com/2e0DeJP
Redux: https://imgur.com/iHLdPau

**Comment by mitchts** [comment]
Race for Victory: Redux includes an additional region which prevents building underneath the map which the original lacks. This would be why the redux version doesn't include this rule as it is physically impossible to do so.
