### ISSUE TITLE
Tab Completion Improvements

### ISSUE THREAD

**Issue by HuManKeat** [StratusNetwork/Issues#153]
![image](https://user-images.githubusercontent.com/18530897/34244534-a09b4a1c-e660-11e7-8df8-956491e43374.png)
**What:**
As of now, tab completion for player names does not provide the names for those that `!senderPlayer.canSee(player)`, so to say; the completion system will not include the names of the players that the CommandSender cannot see. This "vanishing" effect occurs when players use `/toggle obs`, to only be able to see observing friends or none. Because of this, the tab completion will now only include the match participants and the observing friends, and not the names of all the players in the server. This affects commands such as /tp or /msg, where tab completion of player names are highly useful.

**Solution:** 
Within the `org.bukkit.command.Command` class, there is an internal method ` tabComplete0`. According to the [source code spigot provides](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/command/Command.java) it is at exactly L107 and L108 that the collection of online players are filtered and added to the `List<String> matchedPlayers;`. The current filtering runs as so: 
`if ((senderPlayer == null || senderPlayer.canSee(player)) && StringUtil.startsWithIgnoreCase(name, lastWord))` and to resolve this issue, we can modify the predicate to be 
`if ((senderPlayer == null && StringUtil.startsWithIgnoreCase(name, lastWord))`, and modify L108 from: `String name = player.getName();` to `String name = player.getFakeName();`

**Note:** This is untested, but theoretically works.

**Comment by cswhite2000** [comment]
I suppose it would probably be better to make it configurable so we can keep the old behavior on the lobby and have this behavior on pgm servers.
