### ISSUE TITLE
Have development phased maps not record stats

### ISSUE THREAD

**Issue by jexeI** [StratusNetwork/Issues#158]
This would help for testing maps on Mapdev.

**Comment by 2000thehecf1** [comment]
Wouldn't this be an issue on maps like Cake Day (which for some reason happens to be on development)? Clicking on it's name redirects you to a 404 with "standard:development" in the link:
![captura](https://user-images.githubusercontent.com/11505855/34493848-07c677de-efee-11e7-8f81-7045f785cc4c.PNG)
![captura2](https://user-images.githubusercontent.com/11505855/34493856-0b365254-efee-11e7-9919-55cdcb6a8ed0.PNG)

I'd say it would be better just not tracking stats on MapDev and that kind of servers.

**Comment by jexeI** [comment]
All maps on public servers should be in the production phase, I'll fix that

**Comment by Matic0B** [comment]
@JexeI Still an issue for kills on mapdev

**Comment by jexeI** [comment]
@Matic0B Well, stats include kills and deaths and objectives

**Comment by Matic0B** [comment]
@JexeI My bad, that was probably confusing. I was more replying about the production phase issue you mentioned. Sorry

**Comment by mitchts** [comment]
Development servers just need to be disconnected from the production database. This is the same with the punishments from mapdev influencing production, no?
