### ISSUE TITLE
Payload cannot be added as a gamemode in XML.

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/Issues#159]
`<gamemode>payload</gamemode>` to set the gamemode for Payload maps in the XML

https://github.com/StratusNetwork/OCN/pull/40
https://github.com/StratusNetwork/ProjectAres/pull/62

Doesn't seem to work

**Comment by HuManKeat** [comment]
This is because Payload is internally known as koth, and is defined as so in PayloadDefinition. Its `Stream<MapDoc.Gamemode> gamemodes()` method has to be changed to return `Stream.of(MapDoc.Gamemode.payload)`
