### ISSUE TITLE
Item modifiers affect server picker GUI

### ISSUE THREAD

**Issue by jexeI** [StratusNetwork/Issues#160]
![2018-01-04_21 50 32](https://user-images.githubusercontent.com/8964867/34594905-7b8f1cb4-f199-11e7-9ab6-c241c657bea8.png)

**Comment by amactus** [comment]
Care to explain?

**Comment by jexeI** [comment]
@amactus 
```
<item-mods>
  <match>
    <material>spectral arrow</material>
    <modify name="Jexel is awesome" lore="If you don't think so, then ur bad"/>
  </match>
</item-mods>
```

**Comment by mitchts** [comment]
This affects any GUI that uses items, or any item presented to the player for that matter. Apparently this was fixed back on OCN (https://github.com/OvercastNetwork/Issues/issues/2668), but obviously not.
