### ISSUE TITLE
Lobby issues checklist

### ISSUE THREAD

**Issue by Matic0B** [StratusNetwork/Issues#163]
- [ ] Remove village
- [ ] Fix moderation house (one character has no skin, one character has weird legs, player head placed)
- [ ] Fix signs (payload server leads to payload2 not 1, they also don't display properly but that is probably dev related)

Side quest: Disable "/thru"

Checklist for keeping track of issues with the newest lobby, add new ones if necessary.

**Comment by mitchts** [comment]
Village is a result of the lobby generating new chunks. I had generated completely empty chunks over the top of the village to prevent it from showing, but clearly missed the very edges of it. Payload 1 needs to be changed to Payload 0 (and so on), and the issue with them not displaying the server info is completely plugin related.
