### ISSUE TITLE
/stats <Mod> will show their Nicked name

### ISSUE THREAD

**Issue by slayersource** [StratusNetwork/Issues#168]
/stats <Mod> will show their nicked name instead of the mod username

https://youtu.be/8iUQ2rQ_Cb8

- Video by Ivan_O

**Comment by Palmidence** [comment]
https://github.com/StratusNetwork/ProjectAres/pull/45 Was supposed to fix this a while ago. @PotatoStealer ?

**Comment by slayersource** [comment]
I found out today that mods show up on /staff even if nicked. Another player told me this.

**Comment by HuManKeat** [comment]
It shouldn't be happening, I will look into it

**Comment by HuManKeat** [comment]
@slayersource can you get the player to send an image regarding the issue? i can't seem to pinpoint the issue.

**Comment by slayersource** [comment]
Sorry for the inconvenience but it turns out the second one isn't actually happening. It just takes a while to update that I am nicked on /staff. The case I used to make my statement was that someone did /staff after I nicked but before it updated, my bad.

**Comment by OCNsOMEN** [comment]
Players can teleport to nicked players by using their real names:
https://www.youtube.com/watch?v=Spxpa44mJpw&feature=youtu.be
