### ISSUE TITLE
Sounds don't work on 1.8

### ISSUE THREAD

**Issue by BassamR** [StratusNetwork/Issues#173]
Title explains it all, sounds for getting msgs, reports, countdowns, etc don't work (and yes they are turned on in my settings).

Steps to reproduce: just log on with 1.8 and have someone send you a /msg or a /report

**Comment by Antnecb** [comment]
Does this happen on other servers, or just Stratus?

**Comment by BassamR** [comment]
Just Stratus

**Comment by Antnecb** [comment]
Alright; thought it may have been a similar bug I get quite a lot at first but apparently not.

**Comment by jexeI** [comment]
Is there any specific version like 1.8.x?

**Comment by BassamR** [comment]
Not really, I play on 1.8 and 1.8.8 and the bug is there

**Comment by 2000thehecf1** [comment]
Same happens in 1.7 btw
