### ISSUE TITLE
Gold and iron tokens give the same amount of points in Brisked.

### ISSUE THREAD

**Issue by Tomqss** [StratusNetwork/Issues#174]
While the iron one is supposed to give only 6 points when jumping into the scorebox, it gives 12, just as the gold one.

**Comment by jexeI** [comment]
When given an iron ingot, you also wear one on your head. I started off by adding a region right above the scorebox that removes the helmet before you jump in but I realized that 1.7 players can't see it anyways so I commented out that code and changed it to an iron block.
