### ISSUE TITLE
[Relic] Trying to enter blue spawn tunnel as blue shows error

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#176]
When you try to enter the blue spawn tunnel as a blue player on the map "Relic" it shows the error message: "You may not enter the RED TEAM spawn tunnel!"

Might affect the red spawn as well

**Comment by BGMP** [comment]
Apparently two regions's ids were swapped. I've corrected the issue.

Fixed by: https://gitlab.com/stratus/maps/commit/128059208762bda0a7ce42e34b72cb7571a86af6
