### ISSUE TITLE
[Demaroo] People can blockglitch to get outside spawn

### ISSUE THREAD

**Issue by 2000thehecf1** [StratusNetwork/Issues#179]
A lot of people doing it since it's faster than having to go through the normal cobwebs way so would be nice to get it fixed asap.

**Comment by BGMP** [comment]
I've edited the spawn areas and I think It'll fix this problem.

![demaroo](https://user-images.githubusercontent.com/26081543/35498744-46106192-04ae-11e8-9f52-e3627d768b09.png)

https://gitlab.com/stratus/maps/commit/da8b1b974d3f4ab48f50b33da4f8e155160f92dd
