### ISSUE TITLE
Map ratings not being displayed

### ISSUE THREAD

**Issue by 2000thehecf1** [StratusNetwork/Issues#180]
Maps seem to be ordered by best rated in maps page but ratings are not actually appearing.

**Comment by jexeI** [comment]
Some maps don’t have enough ratings for it to become visible on the website.

**Comment by 2000thehecf1** [comment]
Are you sure that's the reason? In Overcast, when that happened, it used to say something like "not enough ratings yet"

**Comment by jexeI** [comment]
That's exactly what the webpage says for maps that don't have enough ratings.

**Comment by 2000thehecf1** [comment]
Not for me
![captura](https://user-images.githubusercontent.com/11505855/35455208-6165ea4a-02d1-11e8-978e-b068c5504ce4.PNG)

**Comment by jexeI** [comment]
Might be a permission thing then, I can see it.

**Comment by cswhite2000** [comment]
This is behaving correctly, map ratings are currently only shown to Map Developers, Junior Developers, and people with admin.
