### ISSUE TITLE
Add gap reward to coastline

### ISSUE THREAD

**Issue by qlados** [StratusNetwork/Issues#181]
the map with 3 mons and no gap reward is stale af because without a sky you cant pvp through the people cos u lack healing. please fix

<killreward>
    <item amount="8">arrow</item>
    <item amount="1">golden apple</item>
</killreward>

**Comment by BGMP** [comment]
I've added this to the map since I've seen it lots of times in chat and I feel it wouldn't be a bad addition to the map at all. Thanks for the feedback!
