### ISSUE TITLE
I can't join the server.

### ISSUE THREAD

**Issue by obrkill** [StratusNetwork/Issues#186]
It's just in this server. I tried with all the versions without any mod installed and it still give me this message
![boceto](https://user-images.githubusercontent.com/36124716/35775479-85a0b9d2-0946-11e8-8347-6ced70fa715c.png) 

I don't know how GitHub works so there is an imgur link: https://imgur.com/a/IB0lk

**Comment by obrkill** [comment]
also this guy has the same problem. https://stratus.network/forums/topics/5a78c54b669e1a00010008d2

**Comment by cswhite2000** [comment]
The issue was an overly broad ipban
