### ISSUE TITLE
[Harvest] Lower Point amount

### ISSUE THREAD

**Issue by slayersource** [StratusNetwork/Issues#187]
With the current limit at 950, the map takes 15 minutes+ every time its played. It should really be lowered to 600 points or something.

**Comment by BGMP** [comment]
I have asked the author, and he agreed to accept the changes, so I decreased it to 650 points, since, in avarage, it should provide a 10 minutes match, but we'll have to test it out, so I'll leave the issue open for now

**Comment by BGMP** [comment]
The map was tested, and still people asked for lowering it even more, so I've lowered the goal score to 300
