### ISSUE TITLE
Desert Country fix/update

### ISSUE THREAD

**Issue by OCNsOMEN** [StratusNetwork/Issues#190]
- Players were able to place iron blocks in the spawn. -That *should* be fixed in this update.

- Updated 1 author (added his new accound because he rarely uses his old one)

- Download: https://www.dropbox.com/s/3ozmdkvbmxzu4g1/desert_country.zip?dl=0

**Comment by jexeI** [comment]
Map updated. Your xml for the iron block fix didn't work, I fixed that in the latest version [here](https://gist.github.com/JexeI/7956f993cb84be0e3a5fa5eaeafca2fc)
