### ISSUE TITLE
Name color changes after clearing nick

### ISSUE THREAD

**Issue by OCNsOMEN** [StratusNetwork/Issues#193]
When players nick in obs or in a  team and unnick in a team with a different team color, they get the old name color on tab (The team lists). The chat is not affected.

- Video: https://www.youtube.com/watch?v=RR_fx6Y_cQE&feature=youtu.be

**Comment by HuManKeat** [comment]
Issue might be using the player's previous(cached) identity. Will look into it, thanks.
