### ISSUE TITLE
[Airship Battle] Chests contain dispensers despite them being disabled

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#194]
The map "Airship Battle" contains dispensers in the chests even though they are disabled on the map.

**Comment by BGMP** [comment]
I'll look into this in some minutes

**Comment by BGMP** [comment]
XML seems to make clear dispensers are forbidden for this map, and so I've removed them from chests.

**Comment by Marcono1234** [comment]
Dispensers would probably be rather overpowered on this map anyways.

**Comment by BGMP** [comment]
They would. That's why they weren't allowed in the first place
