### ISSUE TITLE
I have problems logging in to the servers, I don't know why...

### ISSUE THREAD

**Issue by Joooen** [StratusNetwork/Issues#195]
So a few months ago I wanted to play on the servers. I logged in to minecraft, went in to the server list and double clicked the stratus network server. Then it came up a message... "Internal error, please try again later". I don't understand why it says that. Help me.

- Joen

**Comment by sausage191181** [comment]
Which version are you using, and what's the IP address you're trying to use?

**Comment by Matic0B** [comment]
Please provide your IGN and which version you are using. No need to provide your IP

**Comment by sausage191181** [comment]
Sorry, I meant server IP -_-

**Comment by Joooen** [comment]
I am using play.stratus.network and eu.stratus.network
IGN: Joen

**Comment by Joooen** [comment]
I have tried using 1.7.10 and 1.8.9 and none is working for me.

**Comment by Matic0B** [comment]
Not a server issue, will talk with senior moderators regarding this.

**Comment by eudaldca** [comment]
@Joooen If you want to discuss your infraction(s), file an appeal at https://stratus.network/appeal.
