### ISSUE TITLE
Proto 1.4.3 is causing lag on certain maps with high concentration of block36

### ISSUE THREAD

**Issue by 2000thehecf1** [StratusNetwork/Issues#196]
For some reason, whenever you place a block or literally just click your fps drop a lot on this map, it should be removed asap because it's very annoying to play and obviously makes a lot of people leave.
Edit: I've noticed this happening in NextGen+ as well, maybe something to do with block 36?

**Comment by jexeI** [comment]
This is due to block 36 not being removed in the 1.4.3 proto. Most, if not all lag is fixed when map is downgraded.

**Comment by amactus** [comment]
Due to legacy support, block 36 is no longer used, which should solve this.
