### ISSUE TITLE
[Website] Beta stylesheet breaks layout on small screens

### ISSUE THREAD

**Issue by freundTech** [StratusNetwork/Issues#199]
The current beta layout contains this CSS:
``` css
.container {
    width: 1100px !important;
}
```

Forcing the container to a fixed width completely breaks the layout on small screens:
![screenshot from 2018-03-01 21-04-00](https://user-images.githubusercontent.com/9515067/36867188-b401c4ee-1d94-11e8-964d-abae481d4ca8.png)
![screenshot from 2018-03-01 21-04-18](https://user-images.githubusercontent.com/9515067/36867193-b5cced1c-1d94-11e8-914d-2d9e02f4a34f.png)

With beta features disabled the website looks fine on small screens:
![screenshot from 2018-03-01 21-05-25](https://user-images.githubusercontent.com/9515067/36867207-c04655d0-1d94-11e8-9d35-a548e5f74964.png)
![screenshot from 2018-03-01 21-05-46](https://user-images.githubusercontent.com/9515067/36867208-c21b48a2-1d94-11e8-9cc0-3d45f66c2fcb.png)

**Comment by Matic0B** [comment]
Known and won't be fixed since its a Beta feature.
