### ISSUE TITLE
Void regions not established in Warlock

### ISSUE THREAD

**Issue by CoWinkKeyDinkInc** [StratusNetwork/Issues#2]
![2017-02-03_15 53 13](https://cloud.githubusercontent.com/assets/7586568/22611668/10733820-ea29-11e6-8e14-415ab5dd1a80.png)

![2017-02-03_15 54 03](https://cloud.githubusercontent.com/assets/7586568/22611671/143527b6-ea29-11e6-91ae-6f6e0c40e20c.png)

**Comment by 2000thehecf1** [comment]
That happened on OCN too, it isn't a bug and I don't think it is a problem either.

**Comment by amactus** [comment]
We've moved our map issues back to the [rotations repository](https://github.com/StratusNetwork/Map-Rotations/issues/17)

Any updates on this will be given there
