### ISSUE TITLE
Cant hit the Player

### ISSUE THREAD

**Issue by byRobo** [StratusNetwork/Issues#20]
I was in Blue (can see it in the Chat) and he was red and I wasnt able to hit him. I had that Situation 2-3 Times, sadly I just got one Rec
Video: https://www.youtube.com/watch?v=C9zTt2fz4kA

**Comment by Listegerade** [comment]
Happened to me as well. I'm positive this is some kind of visual glitch: that player was not actually there, you were hitting air.

**Comment by amactus** [comment]
This sounds like lag. We've not heard any other reports of this, so I'm assuming it's a non-issue now
