### ISSUE TITLE
Flat theme issues

### ISSUE THREAD

**Issue by eudaldca** [StratusNetwork/Issues#205]
- [ ] Low contrast in appeals and reports

- [ ] Sessions page highlight has too much contrasted, distracting

- [ ] Personal info in profiles (gender, interests...) text needs more contrast

- [ ] /play page not themed

**Comment by Palmidence** [comment]
Having dyslexia assist and the flat theme enabled simutaneously causes the navbar to shift.

![image](https://user-images.githubusercontent.com/17485345/38784404-5c4726cc-40df-11e8-8d30-d4a3778a3500.png)
