### ISSUE TITLE
Dark Theme Issues

### ISSUE THREAD

**Issue by HuManKeat** [StratusNetwork/Issues#206]
Matic told me to make this waaaay back last year but I just remembered. bummer.
Firstly, we can barely even see the Cirro tag.
[https://i.gyazo.com/7826899fb0ce813e75ce9667397c30bc.png]()
Secondly, recent punishments page is hard to see, especially with appealed punishments.
[https://i.gyazo.com/a15318b8695e6c8760aff9833b9799cf.png]()

**Comment by Matic0B** [comment]
First one won't be fixed, second one should.
