### ISSUE TITLE
No image scaling on match pages

### ISSUE THREAD

**Issue by Siceth** [StratusNetwork/Issues#212]
The thumbnail picture for matches doesn't scale naturally high-resolution images. For example, a Croak match page ([https://stratus.network/matches/ed780557-cb36-44ce-8663-2439ad7592ec](https://stratus.network/matches/ed780557-cb36-44ce-8663-2439ad7592ec)) looks like this:

![](https://images.seth-phillips.com/stratus-matchscaling "")

It seems that adding the `img-responsive` class scales the image down to 300px/auto as expected.

**Comment by jexeI** [comment]
Most images should be uploaded in the correct dimensions (290 x 246). Looks like this map is an exception to the guidelines, I'll fix that.

**Comment by Matic0B** [comment]
Even if the issue in this case is the map image it self, we are in 2018. Things need to be responsive and scale properly.
