### ISSUE TITLE
Players don't get removed from match pages

### ISSUE THREAD

**Issue by Siceth** [StratusNetwork/Issues#213]
I'm not sure if this is a web bug or database/server bug (or even a bug at all -- it might be intentional), but players who've joined a team don't get removed from the match page anytime they leave a team.  This makes for incorrectly reported historical teams and team sizes; on longer games where a team consistently has few players due to people leaving and joining consistently (e.g. The Nile), one team might appear to be double the size of the other.

The best recent example I could find was from [this match](https://stratus.network/matches/da768b79-8c5d-4f70-bf9a-3ade3248c841), where it reports CincoDeMayo, dragonrider455, and myself on both teams when that wasn't at all the case:

![](https://images.seth-phillips.com/stratus-matchactual "Actual match at game end")
versus
![](https://images.seth-phillips.com/stratus-matchwebview "What the website displays")

Again, this could be due to intentional stats caching or something to that effect, but if that's the case, it would be nice to have the match reported as it actually is.

**Comment by jexeI** [comment]
I think this was left intentional since they were once on that team. Either way, I can see how it may cause confusion.
