### ISSUE TITLE
Monday wool rooms maneuverability issue

### ISSUE THREAD

**Issue by BTKingly** [StratusNetwork/Issues#214]
Picture for reference: https://imgur.com/jZQQve5

The chests on the top floor of the wool room are quite hard to get to, due to layout of the wool room (1.5 block gaps to get to ladder from chest barrier thing). The only way to get them is to jump onto the chests, and then jump to the next block diagonally over (to get to the ladder).

**Comment by Palmidence** [comment]
This has been fixed
