### ISSUE TITLE
Ability to build under Jungle Beat

### ISSUE THREAD

**Issue by HuManKeat** [StratusNetwork/Issues#22]
Players are able to build below bedrock level on Jungle Beat and the opposite teams have a really hard time removing the bridges.

**Comment by mitchts** [comment]
I'm not sure how this brings any strategic advantage to the team bridging underneath the bedrock as I can't find anyway to get back up from down there. Unless I'm missing something completely obvious?

**Comment by cswhite2000** [comment]
You can get back up using boats.

**Comment by mitchts** [comment]
Believed to be fixed in https://gitlab.com/stratus/maps/commit/f6b23ba914395d85cdd4f9f8e1794f7d3b6101b8. It's untested but it should work when it goes live.

**Comment by Listegerade** [comment]
The exact same thing happens in maps like Turf Wars or Snowy Wars, and it's always been considered a feature. Why is it different in this case?
