### ISSUE TITLE
Special cape is not visible while playing or spectating in server

### ISSUE THREAD

**Issue by NanuCNS** [StratusNetwork/Issues#222]
My special cape (Translatoe cape) is not displayed nor visible to me while I join the server and playing in the match. 
My local setting on cape visibility is "on" and everything is working perfectly when I'm in server lobby.

PS. I don't know that this problem connected to the last "cape not displayed" problem or not If so I really sorry for duplicating the issue

**Comment by Matic0B** [comment]
Most likely related to https://github.com/StratusNetwork/issues/issues/228
