### ISSUE TITLE
Cape and skin's double layer not showing in 1.8+

### ISSUE THREAD

**Issue by IvanCh123** [StratusNetwork/Issues#228]
It has been like this for at least a year now and it's annoying.

Like I said, it's only in 1.8+, no idea why but it does show in 1.7, so if you are trying to fix this, you might want to start looking at 1.7 and why is it working in that version.

**Comment by NanuCNS** [comment]
There is some weird phenomenon happened which I think directly related to this issue.
I was playing normally in the mixed server with the latest version of Minecraft (1.13.2)
the internet connection and hardware are normal.

Here are what I found:

1. Some players are able to see my cape/second skin layer. (Which is weird considering no one is able to see anybody or there own cape/ssl)

2. Start seeing other player's avatar as my own skin after playing for a while.

![2019-02-28_20 53 24](https://user-images.githubusercontent.com/8971312/53571570-d588e900-3b9b-11e9-9bdc-cc56e8f0c7eb.png)

3. Seeing other players completly look like myself - with cape/ssl normally show

![2019-02-28_20 53 44](https://user-images.githubusercontent.com/8971312/53571579-db7eca00-3b9b-11e9-9ecd-4b1d19d12a02.png)

![2019-02-28_20 54 10](https://user-images.githubusercontent.com/8971312/53571584-dfaae780-3b9b-11e9-9e7e-3efcca344693.png)
