### ISSUE TITLE
Stats Hotbar is not displaying information

### ISSUE THREAD

**Issue by EBGamer** [StratusNetwork/Issues#229]
The stats hot bar is not showing the player's statistics of the match. Instead of showing the kills, deaths, and the killstreak of the player it only says stats.hotbar.
![2018-06-25_01 10 40](https://user-images.githubusercontent.com/40560937/41838247-bd5069a8-7814-11e8-8408-c22d4cd520bd.png)

**Comment by Pugzy** [comment]
Fixed in https://github.com/StratusNetwork/projectares/commit/8150624ce10660e9ac80d99b3a2982bb00fa88be.
