### ISSUE TITLE
Staff can't see team chat in game

### ISSUE THREAD

**Issue by CrazyisCreeps** [StratusNetwork/Issues#230]
It started after the most recent changes to chat (Admin chat across servers). As far as I'm aware, no changes were made to the permission of the ranks that had it in the Data repo, so it must be some internal change that's creating this conflict.

I wasn't sure if you guys are aware of this, since it's been a while since we originally reported it, and it's still an issue.

**Comment by Pugzy** [comment]
Seems this was fixed in https://github.com/StratusNetwork/projectares/commit/3492e9a5b72bf21055900aa5a0412fb63146c673.

**Comment by CrazyisCreeps** [comment]
I'm not sure if that actually fixed it, I'm still unable to see team messages while in observers.
