### ISSUE TITLE
you can drown your teammates on Outback

### ISSUE THREAD

**Issue by jexeI** [StratusNetwork/Issues#234]
![2018-07-18_19 51 11](https://user-images.githubusercontent.com/8964867/42915216-13f822f2-8ac4-11e8-8eea-8fd112ef65e9.png)
You can't get rid of the water because of regions

**Comment by Palmidence** [comment]
This has been fixed: The`allow-world` tag was used in the spawns, which let things flow into it.

**Comment by jexeI** [comment]
close
