### ISSUE TITLE
Warlock needs lapis and XP to enchant

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#237]
There are enchantment tables, but no way to enchant your gear because you lack XP and lapis.

**Comment by jexeI** [comment]
There never was a clear indication of enchanting aside from the table, perhaps just for a decorative look? Back before lapis enchanting, you could only use the table by smelting sand, wood, or stone.

**Comment by jexeI** [comment]
Update: Talked to some mapdevs/devs about it. Yes it was a feature a looong time back, but OCN still had this in rotation above non-lapis enchanting and it was never addressed or fixed there. Assuming enchant tables aren't a big game-changer.
