### ISSUE TITLE
Battle of Tenjin map has some blocks with bad IDs

### ISSUE THREAD

**Issue by haroldp** [StratusNetwork/Issues#24]
On the Battle of Tenjin map, in the outer wall, above the doorway, there are a few blocks with bad block IDs.  They appear to be wood blocks, but they break with a pick rather than an axe, and when they drop, they lose their texture and appear to be huge with the black and pink checkerboard default texture.  Fairy Tales' used to have this same problem.

**Comment by Palmidence** [comment]
Fixed with https://gitlab.com/stratus/maps/commit/3034079c23dfcdc69c3b82a6561ebb5086f34be3

Thanks for reporting it!
