### ISSUE TITLE
Death animation bugged in 1.7/8?

### ISSUE THREAD

**Issue by IvanCh123** [StratusNetwork/Issues#244]
I don't really know if it's only in this two versions, but that's where I've seen it more often. I posted this in #devs, but I guess It would be more useful if I created an issue here.

This is what I'm talking about https://gyazo.com/05a373aaecffc6ca7697c909f452549c

Steps to recreate it:
-Join in 1.7
-Die a few times
-Tadaa

**Comment by Palmidence** [comment]
I believe this is client side.
