### ISSUE TITLE
/games does not work

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#248]
Should list the games that we have, but it doesn't do anything. It's a dead command. Either can display games like UHC and Mixed, or just have a broader scope such as Team Deathmatch, King of the Hill, etc.

**Comment by mitchts** [comment]
That command was to show games that you could queue up for -- eg. Skywars, Micro. As we don't have anything that uses that mechanic, it doesn't display anything. Though maybe it could be used for UHC in the future.

**Comment by AustinLMayes** [comment]
The above commit partially resolves the issue of no message being shown at all. However, I'll leave this open to continue the UHC discussion.
