### ISSUE TITLE
(Minor) Missing Barrier Blocks on Empired

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Issues#25]
In Empired's spawn drop there are a few missing barrier blocks, allowing players to stand on some of the barriers in the drop.
![2017-04-13_16 59 55](https://cloud.githubusercontent.com/assets/26776253/25043322/03996912-20ed-11e7-9f77-2b343f50b45c.png)

**Comment by mitchts** [comment]
Fixed in https://gitlab.com/stratus/maps/commit/d3782c22b85b3e6b68613b2b28fea0671939a3ef
