### ISSUE TITLE
Lobby Gizmo Conditions

### ISSUE THREAD

**Issue by Siceth** [StratusNetwork/Issues#256]
The Headless Horseman and Ghosts gizmos are currently available to everyone in the Lobby (i.e. without needing droplets; can't test the other gizmos since I already have those unlocked).

![](https://images.seth-phillips.com/stratus-halloween.png)

The Headless Horseman in particular doesn't _appear_ to do anything but does crash the client after enough spam clicks, so it clearly does something with the proxy instance's backend.

**Comment by IvanCh123** [comment]
The other gizmos are fine https://gyazo.com/4b3c0b6cd5c90baa0d41ccbe5def64d1

It's just those two

**Comment by AustinLMayes** [comment]
This has been fixed (thanks @PotatoStealer )
