### ISSUE TITLE
RabbitMQ (AMQP) or backend?

### ISSUE THREAD

**Issue by xEndarZzz** [StratusNetwork/Issues#260]
So im having a big issure here....
once i started your fork of PGM i got an error with API: QueueClient is not connected
More information: https://pastebin.com/DSrChJN3
So my first solution is to spent 3 days to build your backend on a ubuntu virtual machine (because windows 10 won't work for some reason)and i set up everything i need (i got tons of errors for example: ruby gem error but i managed to get that solved by installing 16 not 18 using 3 hours)
now i can visit the website using localhost: 3000
And also the api localhost: 3010
But the thing i need is AMQP and not the webiste
So i spent another 3 hours to install and start rabbitmq
and i can now visit localhost: 15672
but port 5672 has an error: ERR_INVALID_HTTP_RESPONSE
now the problem is,
where should i configure the queue client?
src/main/resources/config.yml
or
src/main/java/tc.oc.api.queue/QueueClientConfiguration.java
or
otherthing else?

Please answer because i spent too much time on it and i still haven't solve it :(

**Comment by amactus** [comment]
Our issue tracker is not for providing server assistance.
