### ISSUE TITLE
Block glitching in Golden Drought III.V spawn

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Issues#27]
Several times I've seen players block glitch onto the supply chests in GV3.5 to get out of spawn quicker (example: https://youtu.be/PgsZTaM2sH4). Imo, this should just be made impossible, possibly by extending the walls' height so that you can't jump on top of them to get out of spawn.

**Comment by mitchts** [comment]
Fixed in https://gitlab.com/stratus/maps/commit/0ff8e0bf72593b3e4d4ac72031cc95afe0b3c9c8
