### ISSUE TITLE
GitHub unicode assets moved to a new domain

### ISSUE THREAD

**Issue by Siceth** [StratusNetwork/Issues#276]
Current website implementation for all pure unicode is rendered as an image like:
`<img alt="earth_americas" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f30e.png" style="vertical-align:middle;" width="16" height="16">`

GitHub updated their assets domain (can't find a source to cite, but links are 404'ing) from `assets-cdn.github.com` to `github.githubassets.com`.

**Comment by unixfox** [comment]
You could submit a PR for these two files:
https://github.com/StratusNetwork/web/blob/master/app/assets/javascripts/application/util/emoji.js#L12
https://github.com/StratusNetwork/web/blob/master/app/assets/javascripts/application/util/emoji.js#L12
