### ISSUE TITLE
Wool placing impossible on Dry Outpost

### ISSUE THREAD

**Issue by unixfox** [StratusNetwork/Issues#277]
It's not possible to place the wool on Dry Outpost due to a spawn protection.
Proof of the bug:
[![](https://user-images.githubusercontent.com/4016501/53680205-69f86600-3cd8-11e9-9df9-f5f492244f94.gif)](https://i.imgur.com/0Yn1fmR.gifv)

**Comment by BGMP** [comment]
Should be fixed.
