### ISSUE TITLE
Bridges in different places on GD3

### ISSUE THREAD

**Issue by sharkskill** [StratusNetwork/Issues#286]
![image](https://user-images.githubusercontent.com/8491120/55644693-92d7b380-57ce-11e9-9606-9127023c7cf1.png)
The bridges on the islands closest to the middle islands on each side are in different places according to the team you're on. This is on the public version (Golden Drought III.V) and the competitive version (Golden Drought III:TE).

**Comment by Palmidence** [comment]
@JexeI Was this ever fixed for PGM?
