### ISSUE TITLE
[Bug] HalfGen+

### ISSUE THREAD

**Issue by ItzCal** [StratusNetwork/Issues#30]
tools don't disappear on death
![2017-04-25_16 55 45](https://cloud.githubusercontent.com/assets/22266452/25395609/854ae3d8-29d9-11e7-81b0-87afadf09235.png)

**Comment by mitchts** [comment]
Fixed in https://gitlab.com/stratus/maps/commit/192610f6698607aa8b096209970448c00e2a4e2c
