### ISSUE TITLE
Grand Cannonning Duel issues

### ISSUE THREAD

**Issue by CrazyisCreeps** [StratusNetwork/Issues#300]
I'm going to forget if I don't write it down

- [x] Can't build in arena 3
- [x] Arena 8 didn't teleport winner
- [x] Thus, arena 9 never got a player to start the match
- [ ] Map also lags like hell

Potentially some other issues related to one of the semi final arenas, arena 13 never started either (probably has to do with the latter issues)

**Comment by AustinLMayes** [comment]
- [X] The Map
