### ISSUE TITLE
Can't repair cuboid on Ender Blast

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Issues#31]
On Ender Blast, you get end stone as a kill reward, which is [meant to be used to used to repair your team's cuboid](http://prntscr.com/f7dsmw). However, the map doesn't let you place end stone on your team's cuboid, as shown here: https://youtu.be/9opUuzffm5A

**Comment by mitchts** [comment]
Fixed in https://gitlab.com/stratus/maps/commit/1eeef21e1df2e40f6331f4a1788ecd37b17601e0
