### ISSUE TITLE
Glitchy bow drawing & eating on Unity/leather armor dropping

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Issues#32]
On Unity, sometimes when eating or drawing a bow, [the animation will reset](https://youtu.be/Kqq7UITpQn4). I'm not sure what exactly causes this, but it appears to occur when standing in a corner of a block. I'm assuming this is a map bug since I haven't encountered this issue on any other maps so far.

Also, leather armor drops on the map (in the video I have blue boots on my hotbar).

**Comment by PoseidonsM** [comment]
Armour drops fixed by https://gitlab.com/stratus/maps/commit/4ea34200381b1849872a83e463ea3165994f1655

Couldn't replicate the animation reset, and don't have a clue as to what could make it happen map side. If you notice it happen again feel free to make another issue.
