### ISSUE TITLE
Kick poll goes into negatives until vetoed

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#33]
![](https://i.gyazo.com/0c92da16f879dccbe45aaf2af2ab10eb.png)

Upon starting a poll to kick myself from the server (I was the only one on), I voted against the poll (voted no) and it decided to keep counting even after it reached the time it should have made the decision by. It proceeded to go into the negatives until vetoed.

**Comment by cswhite2000** [comment]
This has been fixed
