### ISSUE TITLE
TNT spawner doesn't work on Wit's Ending, Blue team missing supply chest

### ISSUE THREAD

**Issue by ItzCal** [StratusNetwork/Issues#35]
- [x] TNT spawner at middle doesn't work
- [x] Also, red team has a supply chest infront of spawn whereas blue doesn't

**Comment by Palmidence** [comment]
Reformatted the issue. In the future, we condense each problem to one issue per map.

**Comment by Palmidence** [comment]
Fixed extra supply chest problem

**Comment by BGMP** [comment]
Fixed. I re-added the spawner to the map
