### ISSUE TITLE
Front part of skins and optifine cape not visible

### ISSUE THREAD

**Issue by angelortizau** [StratusNetwork/Issues#4]
any doubts? (idk how it is called but it's the part of the skin where people put glasses and stuff like that)

**Comment by Scap298** [comment]
![2017-02-05_16 18 43](https://cloud.githubusercontent.com/assets/19925532/22630464/2719c52e-ebc0-11e6-9191-776837cbb484.png) For example, in the game looks like that, but doesn't show the glasses as the regular skin like this https://es.namemc.com/profile/Unity298/c9e6
