### ISSUE TITLE
Default right click action of team selection leather helmet is not cancelled placing it in the head armor slot

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#40]
# The bug
The default right click action of the team selection leather helmet is not cancelled or undone causing it to be placed it in the head armor slot.

**Comment by PoseidonsM** [comment]
This is a client side issue, only the first right click will do this, subsequent actions the server has the ability to cancel. Furthermore, this isn't an issue as it is replaced in the inventory when it appears to be used.
