### ISSUE TITLE
Menu items (server and team selection, teleport compass, settings) are not restored when deleted

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#41]
# The bug
The menu items like the server and team selection, the teleport compass and the settings book are not restored when they are deleted and can be moved freely in the inventory. This makes it difficult to use some of the actions when you do not know the commands or there are no commands.

**Comment by ItzaMeLuigi** [comment]
This is not a bug. You are supposed to be allowed to edit your inventory.

**Comment by Marcono1234** [comment]
Is there then an easy way to get these items back (relogging or switching servers is not really easy)? It might be a little difficult especially for new players to figure out what to do in this situation when they for example by accident pressed the drop item key and now cannot join the match anymore.
