### ISSUE TITLE
Spectator: Inventory actions are not cancelled client-side when a second container is opened while one is already open

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#43]
# The bug
Inventory actions like taking items are not cancelled client-side when a second container (like a chest) is opened while one is already open when you are spectating.

# How to reproduce

1. Have a world with two containers close to each other, for example "Airship Ascendance" where double chests are placed above each other
2. Start moving your mouse up or down while looking at the chests and hold right click
→ First one chest inventory appears which is then replaced by the second one
3. Take items from the chest
→ The items are not replaced and you can move them to your inventory

**Comment by PoseidonsM** [comment]
This is a client side bug and we can't do anything to prevent it from happening. You'll find this on any server that has a latency of above 2ms.

**Comment by Marcono1234** [comment]
But if the right clicking actions arrive at the server in the correct order it should know that now a different container is open and correctly handle it, shouldn't it?

**Comment by PoseidonsM** [comment]
Yeah you're right; wouldn't it cause more harm than good though? I'd much prefer to land on the second inventory as sometimes I misclick before my cursor's on the inventory I want to open.

**Comment by Marcono1234** [comment]
I am not saying that this is not the intended behavior, but the fact that inventory actions are not cancelled client-side as spectator then is a little bit strange.

I assumed it might be caused by the server possibly using a wrong `windowId` but since I was not able to reproduce this in a game (there I was able to pick up items from the second opened chest and they were no client-side only items) it might have a different cause.
