### ISSUE TITLE
Back button in "Token Menu" is called "Cancel"

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#46]
# The bug
It appears the back button in every GUI except the "Token Menu" is called "Go Back". In the "Token Menu" it is called "Cancel" despite it acting like a back button as well.

**Comment by Palmidence** [comment]
Looked at it, seems intended. It probably means that when cancelling, it cancels the whole tokens GUI as a whole, rather than just "Go Back" to the menu, since it defines the section you're cancelling.
