### ISSUE TITLE
mapdev: "Options - Preferences" GUI has no "Previous" button

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#48]
# The bug
On the mapdev server (`mapdev.stratus.network`) the "Options - Preferences" GUI has no "Previous" button which every other GUI has. However, clicking at the top left slot still takes you back to the previous GUI.

**Note:** The title of this GUI is also inconsistent with the other sub GUIs of "Options". All other ones only have their title without the "Options - " prefix, for example "Avatars".

**Comment by amactus** [comment]
This is no longer relevant
