### ISSUE TITLE
mapdev: "Speed Changer" has "Next" button despite there not being any options

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#49]
# The bug
On the mapdev server (`mapdev.stratus.network`) the "Speed Changer" sub GUI of "Options" has a "Next" button despite there being no other buttons and therefore no need for a button for the next page.

**Note:** The title ("Speed Changer") also does not match with the item name in the parrent GUI ("Speed").

**Comment by amactus** [comment]
This is intentional. Although currently unsupported, Stratus+ and Stratus- ranks will have more speed options in the future

**Comment by Marcono1234** [comment]
But why is there then a "Next" button when you don't have any options without the ranks. Shouldn't it be based on what options you have?

Also is the inconsistency with the name really intended?
