### ISSUE TITLE
Cant join uneven teams

### ISSUE THREAD

**Issue by ItzCal** [StratusNetwork/Issues#5]
![2017-02-06_17 00 56](https://cloud.githubusercontent.com/assets/22266452/22658031/9060d574-ec90-11e6-90bd-62b69ce414b7.png)

I tried to /obs and /join again so that I would join purple and we could pvp but it kept putting me back on green.

**Comment by Pugzy** [comment]
This is a PGM feature, non-donators are put on the same team every time they join (prevent them from joining and leaving until they get the team they want).
