### ISSUE TITLE
Using item switch key (F) isn't filtered

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#57]
# The bug
If you have your pickaxe in your offhand while moving out of spawn on Verlate it is not cleared.

**Note:** Putting your sword in the 3rd slot will remove it instead.

**Comment by mitchts** [comment]
How are you moving it to the off-hand slot..? It's locked to that slot so it shouldn't be able to be moved.

**Comment by Marcono1234** [comment]
If I remember it correctly you could use the swap hands key (default `F`).

**Comment by Pablete1234** [comment]
The issue is just that pressing "f" should be denied if the item is locked to a slot, has been an issue since 1.9
