### ISSUE TITLE
Fairy Tales 2: Mini: Cannot use lava bucket despite message saying it can be used on center lanes

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#58]
# The bug
When you try to use a lava bucket on "Fairy Tales 2: Mini" it shows the following error:

> You can only place lava on the center lanes.

However, it appears you cannot place the lava anywhere.

**Comment by PoseidonsM** [comment]
Fixed by https://gitlab.com/stratus/maps/commit/77a11c7d7f3ad802df3c44ec70e8cfdfa89522cc
