### ISSUE TITLE
Players can fall infinitely into the void while waiting to respawn

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#59]
It looks like dead player movement is not prevented when you are waiting for the flag, which one of your team members currently has, to be dropped. This can be seen on "Desert Sanctuary 1.4". You are able to move freely and also can fall infinitely in the void instead of starting to fly at y=-64.

**Comment by mitchts** [comment]
```
<respawn spectate="true">
    <message>
        { translate: "death.respawn.confirmed.waiting.flagDropped" }
    </message>
</respawn>
```
They are allowed to move while waiting for the flag to be dropped, however falling into the void infinitely should be considered a bug.

**Comment by Palmidence** [comment]
Could we teleport players who are below Y:-64 to their spawn location on CTF maps and freeze them?

**Comment by mitchts** [comment]
You can't filter dead players, and the whole point of spectate is so that dead players can move around freely. It needs a plugin fix as any XML fix would be too clunky.

**Comment by Palmidence** [comment]
Ah, okay. That makes more sense...
