### ISSUE TITLE
Items are kept in inventory when game ends

### ISSUE THREAD

**Issue by ItzCal** [StratusNetwork/Issues#6]
![2017-02-07_18 53 29](https://cloud.githubusercontent.com/assets/22266452/22753806/577b2862-ee35-11e6-97e8-bcb525cd2926.png)

**Comment by amactus** [comment]
I've not experienced this before. Does it happen to you consistently?

**Comment by ItzCal** [comment]
actually ive only noticed that it happens on some games

**Comment by amactus** [comment]
We've not received any further complaints in this. This could be a map error, or something in an older version of PGM.
