### ISSUE TITLE
Title of player inventory shown as spectator is not updated on death

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#60]
# The bug
The title of a player inventory you are viewing as spectator does not update when the player whose inventory you are viewing dies and becomes a spectator.

In this screenshot you can see that the player already has their spectator items but the title is still team colored. The map was "Cavern".
![player inventory title not updated](https://user-images.githubusercontent.com/11685886/27773355-33321f38-5f78-11e7-9efa-feda2479eba0.png)

**Note:** This might happen when the player normally switches or leaves teams as well.

**Comment by PoseidonsM** [comment]
This isn't a bug or error. When matches are over players still retain their team colour due to them not leaving their team. The only instance in which the colour will change is if it's a blitz map (where after X amount of lives they are removed from their team and placed in observers).

**Comment by Marcono1234** [comment]
I am pretty sure this happened when a player died in a blitz match as well. Hopefully I am able to test this again at some point.
