### ISSUE TITLE
Add anti block glitch technology to Placid Spring

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#62]
Added the map rule to act as a deterrent for now (since it was no longer there).

The idea is to prevent players from using boats or glitching up to the top by using block 36, so essentially update the map to the newest proto and spam block 36 in spawn.

**Comment by PoseidonsM** [comment]
Fixed by https://gitlab.com/stratus/maps/commit/6ec396e7f046f8b6be61e7b4d706abbd26cd176f

**Comment by Palmidence** [comment]
That's just map rules, not making the physical changes/updating the proto :(

**Comment by jexeI** [comment]
Seems like players can no longer place blocks in their spawn with added "abgt" or some sort.
