### ISSUE TITLE
1.7 to 1.12 Rebase Issues

### ISSUE THREAD

**Issue by Electroid** [StratusNetwork/Issues#63]
Current (`1.8-1.12`)
- [x] Disable advancements in chat
- [ ] Add `<requires>` XML tag to require a minecraft version
- [x] `java.lang.NullPointerException: null at tc.oc.pgm.wool.WoolMatchModule.handleWoolCrafting(WoolMatchModule.java:190) ~[?:?]`
- [ ] Unable to pick up certain items (investigate renewables)

Legacy (`1.7`)
- [x] Remind players that `1.7` is not fully supported
- [x] Prevent glitch when frozen mid-air
- [x] Cannot see countdowns
- [ ] Villager crash on Rift (and similar maps)
- [ ] Maybe fix tab list (staff ranks not shown)
- [x] Make titles more noticeable
- [x] Cannot see CTF particles, flag, or carrying flag

Version Specific
- [ ] (`1.8.9`) - Players Crashing when trying to render maps with spawners.

**Comment by elevenchars** [comment]
https://pastebin.com/2L7dvytm
Crash I am getting on rift whenever I get close to the map. Not sure what it is. Does not appear to happen in vanilla. I'm going to try disabling everything but optifine and see what happens

**Comment by elevenchars** [comment]
Still crashes with just optifine.
https://pastebin.com/v0Ys4C9x

**Comment by ItzCal** [comment]
Boats don't work and when you get out of them you can't see the boat but everyone else can
https://youtu.be/tH8OboNFIv8

**Comment by ItzCal** [comment]
Diamond axes maybe other axes as well do very little damage

**Comment by ItzCal** [comment]
Crashed 2 times in a row on the map dynamo using forge 1.8.9 with optifine and 1.7 animations mod

crash report: https://pastebin.com/YxE0z8iC

**Comment by blade00000009** [comment]
Arrow deflection bug using 1.8.9 /w optifine 

https://youtu.be/7Z8QCX3tYwc

**Comment by blade00000009** [comment]
Crashed on Facility multiple times (only when joining to play) using forge with optifine and prplz mousedelay fix for 1.8 

https://pastebin.com/f8dywC4c

**Comment by Marcono1234** [comment]
@blade00000009 I just had the arrow deflection bug myself, it happened directly at the beginning of a new game and I had not died yet. Noel can confirm that. After dying people could shoot me again.

Client version: 1.12

**Comment by Marcono1234** [comment]
Death messages are incorrect.

I had it twice now that when I was shot in the void it said I spleefed myself. Additionally one time it said I spleefed a team member when I did not mine at all.

**Comment by Pablete1234** [comment]
Death messages have nothing to do with version specific stuff, make a separate issue

**Comment by Marcono1234** [comment]
I am pretty sure this started with the version change though.

**Comment by Marcono1234** [comment]
Players cannot pickup items directly at the start of a new game until respawning.

**Comment by Marcono1234** [comment]
~~Bed recipes need to be adjusted. Modify the recipe files to allow the old recipe with any wool and prevent colored beds. < 1.12 players only see an item with missing texture.~~ Also possible don't send block entity data to older versions then.

**Comment by 2000thehecf1** [comment]
Lots of people are complaining about not getting their kills properly and after playing for a while I can confirm that void kills are not working properly

Edit: void kills = void/"fell off a high place"

**Comment by Matic0B** [comment]
1.8.9 clients seem to crash because of spawners

**Comment by Marcono1234** [comment]
Title when a game is over is not visible anymore, MVP however still is.

Client version: 1.12

**Comment by Pablete1234** [comment]
@Marcono1234 Behaviour is going to stay latest version, that means 1.12, beds from now on have to be crafted with the same type of wool, and will return a wool of that color, if you are using an outdated client, you will just not see the color of the bed (it should show as red bed always) but the behaviour continues to be that beds do have colors

**Comment by Marcono1234** [comment]
@Pablete1234 then you will need to remove the meta data when sending the item data to older clients since they are currently seeing missing texture items.

**Comment by Pablete1234** [comment]
@Marcono1234 Yes, that is correct, item translation for beds is not being done correctly, item data should be removed, but no behaviour will change, bed recipes won't change

**Comment by ItzCal** [comment]
When enchantment mutation is active, sweeping edge enchant doesn't show even though the sword has the enchanted glow (not sure if this means the enchantment doesn't work)

**Comment by BassamR** [comment]
Entities cannot be picked up sometimes

**Comment by Palmidence** [comment]
@DiabolicForce Only complaint I saw this on was Grenouille II. Has it occurred anywhere else?

(Apparently it only lets you pick up entities after dying)

**Comment by Szboy** [comment]
@Palmidence Seems this also has to do with golden blocks on GD III.V, people can't seem to pick them up initially.

**Comment by Palmidence** [comment]
@Szboy So this just affects maps that have certain blocks allowed to be broken in spawn?

**Comment by Szboy** [comment]
@Palmidence Not sure, I think we need to test it more.

**Comment by BassamR** [comment]
@Palmidence I've seen it happen so far on fond, gd3.5 and grenouille II (only tried it with gold blocks and not iron). And yes, once you die you can pick them up normally.
EDIT: just tried it with other blocks (dirt, wood, etc) and I can't pick them up as well.

**Comment by Electroid** [comment]
What version can you sometimes not pickup entities?

**Comment by BassamR** [comment]
@Electroid i've only had this issue on 1.12

**Comment by 2000thehecf1** [comment]
I've had this same issue playing on 1.7

**Comment by Marcono1234** [comment]
Is this "one issue for all kind of rebasing issues" really a good idea? It looks like this way some of the bugs are missed. For example I had commented about not being able to pick up items at the beginning of a new game already: https://github.com/StratusNetwork/Issues/issues/63#issuecomment-313410593

**Comment by ItzCal** [comment]
https://youtu.be/N_cyaabqzrg

In the first clip, the guy in the water is inside his blocks that he is placing and in the second clip you can see that the guy bridging is fast bridging but on my screen he shouldn't be able to bridge by looking at his position. (didn't really know how to explain it but i'm sure you can see it)

imo this is a major problem as number 1 it affects gameplay as players won't know where to aim and number 2 because i feel like it would be hard to see the difference between if a player is displaced or if a player is hacking and could see a lot of people getting false banned because of this.

**Comment by ItzCal** [comment]
Pretty sure arrows don't go through team mates on 1.7.10 not sure about other versions
