### ISSUE TITLE
Sounds and boss bars not showing in 1.8.8, along with various other sounds

### ISSUE THREAD

**Issue by BassamR** [StratusNetwork/Issues#64]
The countdown sounds at the beginning of a match are non-existent, and the boss bar at the top of the screen which indicates the time remaining to cycle or time remaining to the end of a match is gone.
There are also no sounds when you receive a pm, and the sound that happens when you die is repeated twice.

I did also check my settings, and all the sounds are turned on.

**Comment by PoseidonsM** [comment]
Please leave future rebase issues on [this thread](https://github.com/StratusNetwork/Issues/issues/63).
