### ISSUE TITLE
My Forge Client crashes on server join

### ISSUE THREAD

**Issue by RoonMoonlight** [StratusNetwork/Issues#65]
When I enter the server on Forge, It crashes. I can't play Stratus for while ;-;, So Can you fix this issues?
Evidence: https://pastebin.com/hjK9bNzG

**Comment by Matic0B** [comment]
Does it work without mods?

**Comment by RoonMoonlight** [comment]
I will try it and reply ASAP.

**Comment by RoonMoonlight** [comment]
Okay, When I tested it, It crashes. Can you fix this issues?

**Comment by Matic0B** [comment]
Can you paste a crash report with a vanilla client (if it crashes without any mods and without forge)

**Comment by RoonMoonlight** [comment]
https://pastebin.com/sZf6LrR9 Here

**Comment by tylerCain** [comment]
I can join with Forge perfectly fine

**Comment by Matic0B** [comment]
Closing this since it's already on https://github.com/StratusNetwork/Issues/issues/63
 - 1.8.9 clients crash because of spawners

You should use a different version (seems like only 1.8.9 is affected so try 1.8.8 or something else)
