### ISSUE TITLE
Switching to observers on the "You died!" screen does not teleport the player to observer spawn.

### ISSUE THREAD

**Issue by Ensix** [StratusNetwork/Issues#68]
Basically the title. If you die and switch to observers with /obs, you just switch to observers at the spot you died. This doesn't seem to happen when you die by falling into the void.

**Comment by PoseidonsM** [comment]
My understanding is that this was intended as if you die to someone that you suspect of cheating you can quickly /obs and then spectate them. The reason it doesn't work in the void is that you wouldn't be able to observer straight away anyway.

**Comment by Palmidence** [comment]
I hope this is intended and not a bug, because @PoseidonsM basically summed it up
