### ISSUE TITLE
Various itemremove bugs on Depths

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Issues#69]
Coal and Emerald blocks (monument materials) aren't on itemremove, neither is stained clay. Also, cooked salmon is on itemremove; I'm assuming this is a bug since you only spawn with 12.
![2017-07-08_21 43 25](https://user-images.githubusercontent.com/26776253/27990547-71d59ef4-6428-11e7-9140-4f2084a9a458.png)
![2017-07-08_21 47 58](https://user-images.githubusercontent.com/26776253/27990548-71d6536c-6428-11e7-8f80-fd6b29be89d0.png)
![2017-07-08_21 42 42](https://user-images.githubusercontent.com/26776253/27990549-71dc465a-6428-11e7-9af4-e03ec00f615b.png)

**Comment by PoseidonsM** [comment]
Fixed by https://gitlab.com/stratus/maps/commit/822980150bec70affa96720f085d0dd01992419f
