### ISSUE TITLE
Incorrect regions on Battle of Tenjin 2

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Issues#71]
There is a chest hidden at the very top of the spawn building, which you are supposed to be able to access by breaking the blocks on top of it; however, due to incorrect regions it's impossible to access the chest https://youtu.be/X4fc9sZK1IA?t=15s

**Comment by PoseidonsM** [comment]
Fixed by https://gitlab.com/stratus/maps/commit/0a17c74105c461a88f78269bb0c45fd08186e29f
