### ISSUE TITLE
Remaining blitz lives translations missing

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#72]
# The bug
The translations for how many blitz lives a player you are currently inspecting has are missing.
`match.blitz.livesRemaining.singularLives`
`match.blitz.livesRemaining.pluralLives`

# How to reproduce
In a blitz match, right click a player while being a spectator and hover over the egg item stack representing their blitz lives.

**Comment by cswhite2000** [comment]
This was fixed a bit ago
