### ISSUE TITLE
The <crafting> module breaks heaps of things

### ISSUE THREAD

**Issue by mitchts** [StratusNetwork/Issues#73]
It might be proto specific, but I haven't tested this with enough maps to be sure. Maps like `Fracture DTM` and `Dam Nation` have monument modes which don't work. The timer in `/modes list` doesn't decrease and no alerts/block changes occur. These monument modes worked previously, and still work on my local PGM server which is running an older version of PGM. These maps are protos `1.4.2` and `1.4.3`, respectively. 

Coastline, which is proto `1.3.2`, also has monument modes, however these work as expected. From this is appears to be a proto specific issue, however Grande (`1.4.3`) has mode changes that work. Grande uses cores instead of monuments though, so this might not be related.

**Comment by mitchts** [comment]
It turns out it's actually the `<crafting>...</crafting>` module that causes this and an array of other issues in various maps (renewables not working, item filters failing...)

**Comment by Palmidence** [comment]
The crafting module does not work still. It prevents wood materials like Sticks and Buttons being crafted on Cold Aunder II, and other maps as well using this module.
