### ISSUE TITLE
Flags are dropped and can be placed on the ground

### ISSUE THREAD

**Issue by BassamR** [StratusNetwork/Issues#75]
On most CTF maps, breaking or placing blocks isn't allowed so when the flag ends up in someone's inventory, nothing happnens. But on maps like Assault, the flag is dropped and can be placed anywhere.
![2017-07-17_14 42 28](https://user-images.githubusercontent.com/18619720/28264908-329e0faa-6afe-11e7-9234-4ca50566e95f.png)
Notice the two flags, the real one where it's supposed (top left) to be and the fake one (bottom right).

**Comment by Palmidence** [comment]
This has been an issue for about 2 years, I think I blame the plugin for making duplicate banners.
