### ISSUE TITLE
Rotations changing at the wrong time and starting with their 1st map instead of the one that's next

### ISSUE THREAD

**Issue by 2000thehecf1** [StratusNetwork/Issues#76]
Medium rotation is supposed to activate at 32 players but instead it does now with 39 people (?), also happening reversely (when changing from medium to mini) so I guess it also happens with mega.

On the other note, rotations are starting always with the first map instead of the one that's next.

**Comment by mitchts** [comment]
![](https://puu.sh/wVXAy/deef67326c.png)
