### ISSUE TITLE
Entities can ride in vehicles, behavior needs to be prevented

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#83]
Due to the crafting module being broken, we need a way to disable villagers entering in boats (most specifically). Should have a feature where it disables certain mobs entering vehicles, since physical map changes aren't working.

**Comment by cswhite2000** [comment]
Fixed by [https://github.com/StratusNetwork/ProjectAres/commit/53e16c4d02a0bfb5f97f6fdf9b079997e4315f57](url)
