### ISSUE TITLE
Add lapis to spawn kit on Mystic Point

### ISSUE THREAD

**Issue by Antnecb** [StratusNetwork/Issues#85]
There is an enchanting table that is currently unusable due to the lack of lapis on the map.
![2017-07-31_17 33 29](https://user-images.githubusercontent.com/26776253/28799517-e715b9f6-7616-11e7-8c85-433660dfbab0.png)

**Comment by PoseidonsM** [comment]
Fixed by https://gitlab.com/stratus/maps/commit/ae71f782f6b8496abc7890a4caccccf4f32ad318
