### ISSUE TITLE
Babylon has too many vines around the map

### ISSUE THREAD

**Issue by Palmidence** [StratusNetwork/Issues#87]
Quite laggy when there's so many vines that are unused.

**Comment by PoseidonsM** [comment]
Do vines still lag if block updates are turned off?

**Comment by Palmidence** [comment]
@PoseidonsM I believe if block updates are turned off it may improve, but I think the lighting errors and sheer fact that they're not rendered as normal blocks may still pose a part of the problem. I think we should trim them only around the map, and maybe cut the amount in half.

**Comment by Palmidence** [comment]
Removed the vines and increased accessibility to the bridge and sides.
