### ISSUE TITLE
Insecure website. SSL-less forums logins.

### ISSUE THREAD

**Issue by ghost** [StratusNetwork/Issues#94]
Please solve, forums has logins and entering passwords would not be secure without it, and https doesn't help since the server doesn't respond.

Easily solved with LetsEncrypt.

**Comment by Pablete1234** [comment]
It's being worked on and will soon be solved. You should always use different and secure passwords for all sites regardless of if there's an ssl cert or not anyways, so other services shouldn't be compromised by this.

**Comment by ghost** [comment]
Almost resolved, https works, all you need is auto https redirects(Cloudflare). Closing when auto redirs.

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
We don’t need Cloudflare to redirect to https, although it would be nice to use Cloudflare.

**Comment by ghost** [comment]
It's not necessary, but since they are already probably using it, they might as well take advantage of it since it's sorta easier.

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
Pretty sure we're not using Cloudflare as of now.

**Comment by 058c37a272bed3464d47f0b01038a16a** [comment]
We are now using Cloudflare 👍
