### ISSUE TITLE
Missing image/wrong image on breathing image in main page.

### ISSUE THREAD

**Issue by ghost** [StratusNetwork/Issues#95]
![image](https://user-images.githubusercontent.com/13290941/30404463-a2ee3ea4-989b-11e7-97cc-90136901c6fd.png)
The image shown is `/images/index/marketing/19.jpg`, when navigating there the 404 page is displayed.
![image](https://user-images.githubusercontent.com/13290941/30404549-fdbbdbde-989b-11e7-99cc-785208924b36.png)
I assume that image is not supposed to be there since the other images have the format of `/assets/index/marketing/14-e487729e9f3676772a3dcf08ff4f3d918f42dc0b350eb41a69739a5af0e80262.jpg`

**Comment by Matic0B** [comment]
We don't even have 19 images so it shouldn't be displaying that anyway.

**Comment by Matic0B** [comment]
Should be fixed now that there are more images, waiting to be deployed.
