### ISSUE TITLE
Teamkilling counts as kills

### ISSUE THREAD

**Issue by ItzCal** [StratusNetwork/Issues#96]
havent actually tested this but when i went onto my profile it said this 
![image](https://user-images.githubusercontent.com/22266452/30523710-fcc326d4-9bdd-11e7-93d1-cca52b9bd0a4.png)

but hunter was on my team and kept dying from my icarus

**Comment by jexeI** [comment]
Are you sure it is affecting your total kills, or just shows up on your pvp encounters?

**Comment by Brottweiler** [comment]
It shows up in pvp encounters, but it doesn't add to your kills or KD/KK.

**Comment by jexeI** [comment]
Because it still counts as a PVP encounter, but doesn’t add to your kills, I don’t think this is an issue.
